source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem "font-awesome-rails"
gem "bootstrap-sass"
gem 'cancancan', '~> 1.10'
gem "faker"
gem 'friendly_id'
gem 'simple_form'
gem 'delayed_job_active_record'
gem "delayed_job_web"
gem 'activeadmin', '~> 1.0.0.pre2'
gem 'devise'
gem 'cocoon'


group :development, :test do
  gem 'byebug'
end

group :development do
  gem "letter_opener"
  gem "rails-erd"
  gem 'web-console', '~> 2.0'
  gem "awesome_print"
  gem "interactive_editor"
  gem "better_errors"

gem "binding_of_caller"
  #gem "hirb"

  gem 'spring'

end
